server:
  port: 4002
  servlet:
    context-path: /foot

spring:
  profiles:
    active:
      - foot
  jpa:
    database: postgresql
    # properties:
    #   hibernate: default_schema:foot
      # jpa-show-sql: true

  datasource:
    url: jdbc:p6spy:postgresql://192.168.3.201:5432/foot?currentSchema=foot
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    # password: jswpass325
    password: jiangsw
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1765000
      connection-timeout: 30000
      connection-test-query: select 1
  servlet:
    multipart:
      location: e://fileResources/

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

mybatis:
  config-location: classpath:mybatis.xml

logging:
  file:
    name: logs/foot.log

swagger:
  enabled: true 