server:
  port: 4001
  servlet:
    context-path: /irr
    session:
      timeout: PT24H

spring:
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
  resources:
    static-locations:
      - classpath:/resources
      - classpath:/static

  jpa:
    database: oracle
    properties:
      hibernate: default_schema:auth
  datasource:
    url: jdbc:p6spy:oracle:thin:@192.168.3.201:1521:ora
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: irr
    password: irr
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1765000
      connection-timeout: 30000
      connection-test-query: SELECT * from dual

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

mybatis:
  config-location: classpath:mybatis.xml

logging:
  file:
    name: logs/irr.log
